name:                twitter-bot
version:             0.1.0.0
github:              "acidjunk/twitter-bot"
license:             BSD3
author:              "René Dohmen"
maintainer:          "acidjunk@gmail.com"
copyright:           "2022 René Dohmen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/twitter-bot#readme>

dependencies:
- base >= 4.7 && < 5
- tweet-hs
- aeson

library:
  source-dirs: src

executables:
  twitter-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twitter-bot

tests:
  twitter-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twitter-bot
